import { Article } from "@/src/types/real-estate";

export const mockProperties: Article[] = [
  {
    _id: "mock-id-1",
    article_no: "24-00001",
    article_id: "A0000001",
    article_title: "강남구 역삼동, 넓고 깨끗한 원룸",
    article_short_description: "역세권, 풀옵션, 즉시입주 가능. 혼자 살기 딱 좋은 방입니다.",
    agent_office: "행복 부동산 1호점",
    agent_hp: "010-1234-0001",
    article_short_features: ["역세권", "풀옵션", "단기임대"],
    article_class: "원룸",
    article_regist_date: "2024-10-01",
    agent_office_post: "공인중개사",
    deposit_fee: 5000,
    rent_fee: 80,
    management_fee: "5",
    gu: "강남구",
    dong: "역삼동",
    floor: "3/5층",
    exclusive_area: "25.5m²",
    direction: "남향",
    transaction_type: "월세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+1",
    possible_move: "즉시입주",
    tag_list: ["#역세권", "#깨끗함", "#보안철저"],
  },
  {
    _id: "mock-id-2",
    article_no: "24-00002",
    article_id: "A0000002",
    article_title: "서초구 반포동, 한강뷰 아파트 전세",
    article_short_description: "채광 좋은 3룸 아파트, 학군 좋고 교통 편리합니다.",
    agent_office: "베스트 공인중개사 2호점",
    agent_hp: "010-1234-0002",
    article_short_features: ["한강뷰", "학군우수", "로얄층"],
    article_class: "아파트",
    article_regist_date: "2024-10-02",
    agent_office_post: "공인중개사",
    deposit_fee: 80000,
    rent_fee: 0,
    management_fee: "25",
    gu: "서초구",
    dong: "반포동",
    floor: "15/28층",
    exclusive_area: "84.9m²",
    direction: "남동향",
    transaction_type: "전세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+2",
    possible_move: "날짜협의",
    tag_list: ["#한강뷰", "#대단지", "#학군"],
  },
  {
    _id: "mock-id-3",
    article_no: "24-00003",
    article_id: "A0000003",
    article_title: "마포구 합정동, 신축 오피스텔 월세",
    article_short_description: "합정역 도보 3분 거리의 신축 오피스텔입니다. 보안이 좋습니다.",
    agent_office: "친절 공인중개사 3호점",
    agent_hp: "010-1234-0003",
    article_short_features: ["신축", "역세권", "보안철저"],
    article_class: "오피스텔",
    article_regist_date: "2024-10-03",
    agent_office_post: "공인중개사",
    deposit_fee: 2000,
    rent_fee: 120,
    management_fee: "10",
    gu: "마포구",
    dong: "합정동",
    floor: "10/15층",
    exclusive_area: "33.0m²",
    direction: "서향",
    transaction_type: "월세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+3",
    possible_move: "즉시입주",
    tag_list: ["#신축", "#역세권", "#보안굿"],
  },
  {
    _id: "mock-id-4",
    article_no: "24-00004",
    article_id: "A0000004",
    article_title: "성동구 성수동1가, 감성 투룸 전세",
    article_short_description: "리모델링 완료된 감성적인 투룸입니다. 서울숲이 가깝습니다.",
    agent_office: "스타일 부동산 4호점",
    agent_hp: "010-1234-0004",
    article_short_features: ["리모델링", "서울숲인근", "조용한주택가"],
    article_class: "투룸",
    article_regist_date: "2024-10-04",
    agent_office_post: "공인중개사",
    deposit_fee: 45000,
    rent_fee: 0,
    management_fee: "3",
    gu: "성동구",
    dong: "성수동1가",
    floor: "2/4층",
    exclusive_area: "45.2m²",
    direction: "동향",
    transaction_type: "전세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+4",
    possible_move: "날짜협의",
    tag_list: ["#리모델링", "#서울숲", "#감성"],
  },
  {
    _id: "mock-id-5",
    article_no: "24-00005",
    article_id: "A0000005",
    article_title: "용산구 한남동, 고급빌라 매매",
    article_short_description: "조용하고 프라이빗한 환경의 고급 빌라입니다. 최고의 주거 환경.",
    agent_office: "프리미엄 공인중개사 5호점",
    agent_hp: "010-1234-0005",
    article_short_features: ["고급빌라", "프라이빗", "주차편리"],
    article_class: "빌라",
    article_regist_date: "2024-10-05",
    agent_office_post: "공인중개사",
    deposit_fee: 250000,
    rent_fee: 0,
    management_fee: "50",
    gu: "용산구",
    dong: "한남동",
    floor: "4/6층",
    exclusive_area: "150.0m²",
    direction: "남향",
    transaction_type: "매매",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+5",
    possible_move: "날짜협의",
    tag_list: ["#고급빌라", "#조용한", "#주차"],
  },
  // Adding more data
  {
    _id: "mock-id-6",
    article_no: "24-00006",
    article_id: "A0000006",
    article_title: "강남구 논현동, 가성비 좋은 오피스텔",
    article_short_description: "강남 업무지구 접근성 최고! 가성비 좋은 오피스텔입니다.",
    agent_office: "행복 부동산 1호점",
    agent_hp: "010-1234-0006",
    article_short_features: ["가성비", "업무지구인근"],
    article_class: "오피스텔",
    article_regist_date: "2024-10-06",
    agent_office_post: "공인중개사",
    deposit_fee: 1000,
    rent_fee: 90,
    management_fee: "8",
    gu: "강남구",
    dong: "논현동",
    floor: "8/12층",
    exclusive_area: "28.0m²",
    direction: "북향",
    transaction_type: "월세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+6",
    possible_move: "즉시입주",
    tag_list: ["#가성비", "#강남"],
  },
  {
    _id: "mock-id-7",
    article_no: "24-00007",
    article_id: "A0000007",
    article_title: "마포구 서교동, 홍대 인근 투룸",
    article_short_description: "홍대입구역과 가까운 투룸입니다. 친구와 함께 살기 좋아요.",
    agent_office: "친절 공인중개사 3호점",
    agent_hp: "010-1234-0007",
    article_short_features: ["홍대인근", "역세권"],
    article_class: "투룸",
    article_regist_date: "2024-10-07",
    agent_office_post: "공인중개사",
    deposit_fee: 20000,
    rent_fee: 0,
    management_fee: "7",
    gu: "마포구",
    dong: "서교동",
    floor: "4/5층",
    exclusive_area: "50.5m²",
    direction: "서향",
    transaction_type: "전세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+7",
    possible_move: "날짜협의",
    tag_list: ["#홍대", "#역세권", "#투룸"],
  },
  {
    _id: "mock-id-8",
    article_no: "24-00008",
    article_id: "A0000008",
    article_title: "서초구 서초동, 법원 앞 아파트 매매",
    article_short_description: "서초 법원 및 검찰청 인근 아파트. 투자 가치 높음.",
    agent_office: "베스트 공인중개사 2호점",
    agent_hp: "010-1234-0008",
    article_short_features: ["투자추천", "법원인근"],
    article_class: "아파트",
    article_regist_date: "2024-10-08",
    agent_office_post: "공인중개사",
    deposit_fee: 180000,
    rent_fee: 0,
    management_fee: "30",
    gu: "서초구",
    dong: "서초동",
    floor: "7/20층",
    exclusive_area: "110.0m²",
    direction: "남향",
    transaction_type: "매매",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+8",
    possible_move: "날짜협의",
    tag_list: ["#투자", "#서초동", "#아파트"],
  },
  {
    _id: "mock-id-9",
    article_no: "24-00009",
    article_id: "A0000009",
    article_title: "성동구 왕십리동, 초역세권 원룸",
    article_short_description: "왕십리역 도보 1분! 교통의 중심, 말이 필요없는 위치.",
    agent_office: "스타일 부동산 4호점",
    agent_hp: "010-1234-0009",
    article_short_features: ["초역세권", "교통최고"],
    article_class: "원룸",
    article_regist_date: "2024-10-09",
    agent_office_post: "공인중개사",
    deposit_fee: 3000,
    rent_fee: 70,
    management_fee: "6",
    gu: "성동구",
    dong: "왕십리동",
    floor: "5/7층",
    exclusive_area: "22.0m²",
    direction: "동향",
    transaction_type: "월세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+9",
    possible_move: "즉시입주",
    tag_list: ["#왕십리", "#초역세권"],
  },
  {
    _id: "mock-id-10",
    article_no: "24-00010",
    article_id: "A0000010",
    article_title: "용산구 이태원동, 해방촌 유니크 빌라",
    article_short_description: "해방촌의 자유로운 감성을 담은 유니크한 빌라입니다.",
    agent_office: "프리미엄 공인중개사 5호점",
    agent_hp: "010-1234-0010",
    article_short_features: ["해방촌", "유니크인테리어"],
    article_class: "빌라",
    article_regist_date: "2024-10-10",
    agent_office_post: "공인중개사",
    deposit_fee: 35000,
    rent_fee: 0,
    management_fee: "5",
    gu: "용산구",
    dong: "이태원동",
    floor: "1/3층",
    exclusive_area: "60.8m²",
    direction: "남서향",
    transaction_type: "전세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+10",
    possible_move: "날짜협의",
    tag_list: ["#해방촌", "#감성", "#인테리어"],
  },
  {
    _id: "mock-id-11",
    article_no: "24-00011",
    article_id: "A0000011",
    article_title: "강남구 삼성동, 코엑스 인근 오피스텔",
    article_short_description: "코엑스와 현대백화점이 가까운 최신 오피스텔입니다.",
    agent_office: "행복 부동산 1호점",
    agent_hp: "010-1234-0011",
    article_short_features: ["코엑스인근", "신축"],
    article_class: "오피스텔",
    article_regist_date: "2024-10-11",
    agent_office_post: "공인중개사",
    deposit_fee: 10000,
    rent_fee: 150,
    management_fee: "15",
    gu: "강남구",
    dong: "삼성동",
    floor: "12/20층",
    exclusive_area: "40.0m²",
    direction: "북동향",
    transaction_type: "월세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+11",
    possible_move: "즉시입주",
    tag_list: ["#코엑스", "#신축", "#오피스텔"],
  },
  {
    _id: "mock-id-12",
    article_no: "24-00012",
    article_id: "A0000012",
    article_title: "마포구 망원동, 망리단길 힙한 원룸",
    article_short_description: "망리단길에 위치한 힙한 원룸. 주변에 맛집과 카페가 많아요.",
    agent_office: "친절 공인중개사 3호점",
    agent_hp: "010-1234-0012",
    article_short_features: ["망리단길", "인테리어굿"],
    article_class: "원룸",
    article_regist_date: "2024-10-12",
    agent_office_post: "공인중개사",
    deposit_fee: 5000,
    rent_fee: 60,
    management_fee: "5",
    gu: "마포구",
    dong: "망원동",
    floor: "2/4층",
    exclusive_area: "23.0m²",
    direction: "남향",
    transaction_type: "월세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+12",
    possible_move: "날짜협의",
    tag_list: ["#망리단길", "#힙스터", "#추천"],
  },
  {
    _id: "mock-id-13",
    article_no: "24-00013",
    article_id: "A0000013",
    article_title: "서초구 방배동, 조용한 주택가 투룸 전세",
    article_short_description: "조용하고 쾌적한 주택가에 위치한 투룸입니다. 신혼부부 추천.",
    agent_office: "베스트 공인중개사 2호점",
    agent_hp: "010-1234-0013",
    article_short_features: ["조용한주택가", "신혼부부추천"],
    article_class: "투룸",
    article_regist_date: "2024-10-13",
    agent_office_post: "공인중개사",
    deposit_fee: 55000,
    rent_fee: 0,
    management_fee: "10",
    gu: "서초구",
    dong: "방배동",
    floor: "3/5층",
    exclusive_area: "55.0m²",
    direction: "동향",
    transaction_type: "전세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+13",
    possible_move: "날짜협의",
    tag_list: ["#신혼부부", "#조용한", "#투룸"],
  },
  {
    _id: "mock-id-14",
    article_no: "24-00014",
    article_id: "A0000014",
    article_title: "성동구 금호동, 리버뷰 아파트",
    article_short_description: "거실에서 한강이 보이는 리버뷰 아파트입니다. 전망 최고.",
    agent_office: "스타일 부동산 4호점",
    agent_hp: "010-1234-0014",
    article_short_features: ["리버뷰", "전망좋은"],
    article_class: "아파트",
    article_regist_date: "2024-10-14",
    agent_office_post: "공인중개사",
    deposit_fee: 120000,
    rent_fee: 0,
    management_fee: "35",
    gu: "성동구",
    dong: "금호동",
    floor: "21/35층",
    exclusive_area: "84.0m²",
    direction: "남향",
    transaction_type: "전세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+14",
    possible_move: "2025-01-01",
    tag_list: ["#리버뷰", "#전망", "#아파트"],
  },
  {
    _id: "mock-id-15",
    article_no: "24-00015",
    article_id: "A0000015",
    article_title: "용산구 후암동, 남산타워 보이는 원룸",
    article_short_description: "창문으로 남산타워가 보이는 낭만적인 원룸입니다.",
    agent_office: "프리미엄 공인중개사 5호점",
    agent_hp: "010-1234-0015",
    article_short_features: ["남산뷰", "낭만"],
    article_class: "원룸",
    article_regist_date: "2024-10-15",
    agent_office_post: "공인중개사",
    deposit_fee: 1000,
    rent_fee: 85,
    management_fee: "7",
    gu: "용산구",
    dong: "후암동",
    floor: "5/5층",
    exclusive_area: "28.0m²",
    direction: "남동향",
    transaction_type: "월세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+15",
    possible_move: "즉시입주",
    tag_list: ["#남산뷰", "#용산", "#원룸"],
  },
  {
    _id: "mock-id-1",
    article_no: "24-00001",
    article_id: "A0000001",
    article_title: "강남구 역삼동, 넓고 깨끗한 원룸",
    article_short_description: "역세권, 풀옵션, 즉시입주 가능. 혼자 살기 딱 좋은 방입니다.",
    agent_office: "행복 부동산 1호점",
    agent_hp: "010-1234-0001",
    article_short_features: ["역세권", "풀옵션", "단기임대"],
    article_class: "원룸",
    article_regist_date: "2024-10-01",
    agent_office_post: "공인중개사",
    deposit_fee: 5000,
    rent_fee: 80,
    management_fee: "5",
    gu: "강남구",
    dong: "역삼동",
    floor: "3/5층",
    exclusive_area: "25.5m²",
    direction: "남향",
    transaction_type: "월세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+1",
    possible_move: "즉시입주",
    tag_list: ["#역세권", "#깨끗함", "#보안철저"],
  },
  {
    _id: "mock-id-2",
    article_no: "24-00002",
    article_id: "A0000002",
    article_title: "서초구 반포동, 한강뷰 아파트 전세",
    article_short_description: "채광 좋은 3룸 아파트, 학군 좋고 교통 편리합니다.",
    agent_office: "베스트 공인중개사 2호점",
    agent_hp: "010-1234-0002",
    article_short_features: ["한강뷰", "학군우수", "로얄층"],
    article_class: "아파트",
    article_regist_date: "2024-10-02",
    agent_office_post: "공인중개사",
    deposit_fee: 80000,
    rent_fee: 0,
    management_fee: "25",
    gu: "서초구",
    dong: "반포동",
    floor: "15/28층",
    exclusive_area: "84.9m²",
    direction: "남동향",
    transaction_type: "전세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+2",
    possible_move: "날짜협의",
    tag_list: ["#한강뷰", "#대단지", "#학군"],
  },
  {
    _id: "mock-id-3",
    article_no: "24-00003",
    article_id: "A0000003",
    article_title: "마포구 합정동, 신축 오피스텔 월세",
    article_short_description: "합정역 도보 3분 거리의 신축 오피스텔입니다. 보안이 좋습니다.",
    agent_office: "친절 공인중개사 3호점",
    agent_hp: "010-1234-0003",
    article_short_features: ["신축", "역세권", "보안철저"],
    article_class: "오피스텔",
    article_regist_date: "2024-10-03",
    agent_office_post: "공인중개사",
    deposit_fee: 2000,
    rent_fee: 120,
    management_fee: "10",
    gu: "마포구",
    dong: "합정동",
    floor: "10/15층",
    exclusive_area: "33.0m²",
    direction: "서향",
    transaction_type: "월세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+3",
    possible_move: "즉시입주",
    tag_list: ["#신축", "#역세권", "#보안굿"],
  },
  {
    _id: "mock-id-4",
    article_no: "24-00004",
    article_id: "A0000004",
    article_title: "성동구 성수동1가, 감성 투룸 전세",
    article_short_description: "리모델링 완료된 감성적인 투룸입니다. 서울숲이 가깝습니다.",
    agent_office: "스타일 부동산 4호점",
    agent_hp: "010-1234-0004",
    article_short_features: ["리모델링", "서울숲인근", "조용한주택가"],
    article_class: "투룸",
    article_regist_date: "2024-10-04",
    agent_office_post: "공인중개사",
    deposit_fee: 45000,
    rent_fee: 0,
    management_fee: "3",
    gu: "성동구",
    dong: "성수동1가",
    floor: "2/4층",
    exclusive_area: "45.2m²",
    direction: "동향",
    transaction_type: "전세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+4",
    possible_move: "날짜협의",
    tag_list: ["#리모델링", "#서울숲", "#감성"],
  },
  {
    _id: "mock-id-5",
    article_no: "24-00005",
    article_id: "A0000005",
    article_title: "용산구 한남동, 고급빌라 매매",
    article_short_description: "조용하고 프라이빗한 환경의 고급 빌라입니다. 최고의 주거 환경.",
    agent_office: "프리미엄 공인중개사 5호점",
    agent_hp: "010-1234-0005",
    article_short_features: ["고급빌라", "프라이빗", "주차편리"],
    article_class: "빌라",
    article_regist_date: "2024-10-05",
    agent_office_post: "공인중개사",
    deposit_fee: 250000,
    rent_fee: 0,
    management_fee: "50",
    gu: "용산구",
    dong: "한남동",
    floor: "4/6층",
    exclusive_area: "150.0m²",
    direction: "남향",
    transaction_type: "매매",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+5",
    possible_move: "날짜협의",
    tag_list: ["#고급빌라", "#조용한", "#주차"],
  },
  // Adding more data
  {
    _id: "mock-id-6",
    article_no: "24-00006",
    article_id: "A0000006",
    article_title: "강남구 논현동, 가성비 좋은 오피스텔",
    article_short_description: "강남 업무지구 접근성 최고! 가성비 좋은 오피스텔입니다.",
    agent_office: "행복 부동산 1호점",
    agent_hp: "010-1234-0006",
    article_short_features: ["가성비", "업무지구인근"],
    article_class: "오피스텔",
    article_regist_date: "2024-10-06",
    agent_office_post: "공인중개사",
    deposit_fee: 1000,
    rent_fee: 90,
    management_fee: "8",
    gu: "강남구",
    dong: "논현동",
    floor: "8/12층",
    exclusive_area: "28.0m²",
    direction: "북향",
    transaction_type: "월세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+6",
    possible_move: "즉시입주",
    tag_list: ["#가성비", "#강남"],
  },
  {
    _id: "mock-id-7",
    article_no: "24-00007",
    article_id: "A0000007",
    article_title: "마포구 서교동, 홍대 인근 투룸",
    article_short_description: "홍대입구역과 가까운 투룸입니다. 친구와 함께 살기 좋아요.",
    agent_office: "친절 공인중개사 3호점",
    agent_hp: "010-1234-0007",
    article_short_features: ["홍대인근", "역세권"],
    article_class: "투룸",
    article_regist_date: "2024-10-07",
    agent_office_post: "공인중개사",
    deposit_fee: 20000,
    rent_fee: 0,
    management_fee: "7",
    gu: "마포구",
    dong: "서교동",
    floor: "4/5층",
    exclusive_area: "50.5m²",
    direction: "서향",
    transaction_type: "전세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+7",
    possible_move: "날짜협의",
    tag_list: ["#홍대", "#역세권", "#투룸"],
  },
  {
    _id: "mock-id-8",
    article_no: "24-00008",
    article_id: "A0000008",
    article_title: "서초구 서초동, 법원 앞 아파트 매매",
    article_short_description: "서초 법원 및 검찰청 인근 아파트. 투자 가치 높음.",
    agent_office: "베스트 공인중개사 2호점",
    agent_hp: "010-1234-0008",
    article_short_features: ["투자추천", "법원인근"],
    article_class: "아파트",
    article_regist_date: "2024-10-08",
    agent_office_post: "공인중개사",
    deposit_fee: 180000,
    rent_fee: 0,
    management_fee: "30",
    gu: "서초구",
    dong: "서초동",
    floor: "7/20층",
    exclusive_area: "110.0m²",
    direction: "남향",
    transaction_type: "매매",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+8",
    possible_move: "날짜협의",
    tag_list: ["#투자", "#서초동", "#아파트"],
  },
  {
    _id: "mock-id-9",
    article_no: "24-00009",
    article_id: "A0000009",
    article_title: "성동구 왕십리동, 초역세권 원룸",
    article_short_description: "왕십리역 도보 1분! 교통의 중심, 말이 필요없는 위치.",
    agent_office: "스타일 부동산 4호점",
    agent_hp: "010-1234-0009",
    article_short_features: ["초역세권", "교통최고"],
    article_class: "원룸",
    article_regist_date: "2024-10-09",
    agent_office_post: "공인중개사",
    deposit_fee: 3000,
    rent_fee: 70,
    management_fee: "6",
    gu: "성동구",
    dong: "왕십리동",
    floor: "5/7층",
    exclusive_area: "22.0m²",
    direction: "동향",
    transaction_type: "월세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+9",
    possible_move: "즉시입주",
    tag_list: ["#왕십리", "#초역세권"],
  },
  {
    _id: "mock-id-10",
    article_no: "24-00010",
    article_id: "A0000010",
    article_title: "용산구 이태원동, 해방촌 유니크 빌라",
    article_short_description: "해방촌의 자유로운 감성을 담은 유니크한 빌라입니다.",
    agent_office: "프리미엄 공인중개사 5호점",
    agent_hp: "010-1234-0010",
    article_short_features: ["해방촌", "유니크인테리어"],
    article_class: "빌라",
    article_regist_date: "2024-10-10",
    agent_office_post: "공인중개사",
    deposit_fee: 35000,
    rent_fee: 0,
    management_fee: "5",
    gu: "용산구",
    dong: "이태원동",
    floor: "1/3층",
    exclusive_area: "60.8m²",
    direction: "남서향",
    transaction_type: "전세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+10",
    possible_move: "날짜협의",
    tag_list: ["#해방촌", "#감성", "#인테리어"],
  },
  {
    _id: "mock-id-11",
    article_no: "24-00011",
    article_id: "A0000011",
    article_title: "강남구 삼성동, 코엑스 인근 오피스텔",
    article_short_description: "코엑스와 현대백화점이 가까운 최신 오피스텔입니다.",
    agent_office: "행복 부동산 1호점",
    agent_hp: "010-1234-0011",
    article_short_features: ["코엑스인근", "신축"],
    article_class: "오피스텔",
    article_regist_date: "2024-10-11",
    agent_office_post: "공인중개사",
    deposit_fee: 10000,
    rent_fee: 150,
    management_fee: "15",
    gu: "강남구",
    dong: "삼성동",
    floor: "12/20층",
    exclusive_area: "40.0m²",
    direction: "북동향",
    transaction_type: "월세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+11",
    possible_move: "즉시입주",
    tag_list: ["#코엑스", "#신축", "#오피스텔"],
  },
  {
    _id: "mock-id-12",
    article_no: "24-00012",
    article_id: "A0000012",
    article_title: "마포구 망원동, 망리단길 힙한 원룸",
    article_short_description: "망리단길에 위치한 힙한 원룸. 주변에 맛집과 카페가 많아요.",
    agent_office: "친절 공인중개사 3호점",
    agent_hp: "010-1234-0012",
    article_short_features: ["망리단길", "인테리어굿"],
    article_class: "원룸",
    article_regist_date: "2024-10-12",
    agent_office_post: "공인중개사",
    deposit_fee: 5000,
    rent_fee: 60,
    management_fee: "5",
    gu: "마포구",
    dong: "망원동",
    floor: "2/4층",
    exclusive_area: "23.0m²",
    direction: "남향",
    transaction_type: "월세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+12",
    possible_move: "날짜협의",
    tag_list: ["#망리단길", "#힙스터", "#추천"],
  },
  {
    _id: "mock-id-13",
    article_no: "24-00013",
    article_id: "A0000013",
    article_title: "서초구 방배동, 조용한 주택가 투룸 전세",
    article_short_description: "조용하고 쾌적한 주택가에 위치한 투룸입니다. 신혼부부 추천.",
    agent_office: "베스트 공인중개사 2호점",
    agent_hp: "010-1234-0013",
    article_short_features: ["조용한주택가", "신혼부부추천"],
    article_class: "투룸",
    article_regist_date: "2024-10-13",
    agent_office_post: "공인중개사",
    deposit_fee: 55000,
    rent_fee: 0,
    management_fee: "10",
    gu: "서초구",
    dong: "방배동",
    floor: "3/5층",
    exclusive_area: "55.0m²",
    direction: "동향",
    transaction_type: "전세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+13",
    possible_move: "날짜협의",
    tag_list: ["#신혼부부", "#조용한", "#투룸"],
  },
  {
    _id: "mock-id-14",
    article_no: "24-00014",
    article_id: "A0000014",
    article_title: "성동구 금호동, 리버뷰 아파트",
    article_short_description: "거실에서 한강이 보이는 리버뷰 아파트입니다. 전망 최고.",
    agent_office: "스타일 부동산 4호점",
    agent_hp: "010-1234-0014",
    article_short_features: ["리버뷰", "전망좋은"],
    article_class: "아파트",
    article_regist_date: "2024-10-14",
    agent_office_post: "공인중개사",
    deposit_fee: 120000,
    rent_fee: 0,
    management_fee: "35",
    gu: "성동구",
    dong: "금호동",
    floor: "21/35층",
    exclusive_area: "84.0m²",
    direction: "남향",
    transaction_type: "전세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+14",
    possible_move: "2025-01-01",
    tag_list: ["#리버뷰", "#전망", "#아파트"],
  },
  {
    _id: "mock-id-15",
    article_no: "24-00015",
    article_id: "A0000015",
    article_title: "용산구 후암동, 남산타워 보이는 원룸",
    article_short_description: "창문으로 남산타워가 보이는 낭만적인 원룸입니다.",
    agent_office: "프리미엄 공인중개사 5호점",
    agent_hp: "010-1234-0015",
    article_short_features: ["남산뷰", "낭만"],
    article_class: "원룸",
    article_regist_date: "2024-10-15",
    agent_office_post: "공인중개사",
    deposit_fee: 1000,
    rent_fee: 85,
    management_fee: "7",
    gu: "용산구",
    dong: "후암동",
    floor: "5/5층",
    exclusive_area: "28.0m²",
    direction: "남동향",
    transaction_type: "월세",
    image_url: "https://via.placeholder.com/400x300.png?text=매물+15",
    possible_move: "즉시입주",
    tag_list: ["#남산뷰", "#용산", "#원룸"],
  },
];
